### ISSUE TITLE
Issue 3 tp6 crear crud para servicios y consejos

### ISSUE THREAD

**Issue by fedewf1** [fedewf1/repositorio-tp2#61]
Agregar el crud para servicios y consejos. Documentar el codigo.

**Comment by JohnRM992** [comment]
Para cumplir con este objetivo se crean las siguientes ramas:

tp6_issue3_crud_servicios

tp6_issue3_crud_consejos


Se  incluye el agregado y/o modificación de ServicioController, ConsejoController en la capa Controller.
El agregado y/o modificación de las clases Servicio y Consejo en la capa Model.
Finalmente el agregado y/o modificación de clases ListaServicio ListaConsejo en paquete Listas
