### ISSUE TITLE
Issue 4 tp6 crear interfaz para IConsejoService, IServicioServic y clases IConsejoService, IServicioServic

### ISSUE THREAD

**Issue by fedewf1** [fedewf1/repositorio-tp2#62]
En el paquete service cree las interfaces necesarias para declarar los métodos.
IConsejoService
IServicioServic

 La declaración de métodos abstractos dentro de las interfaces deben permitir implementar en las clases de
service.imp las siguientes acciones:
Listar, guardar, modificar, eliminar, buscar (por algún criterio), recuperar un objeto del model.

 En el paquete service.imp cree las clases que implementen las interfaces
ConsejoServiceImp
ServicioServiceImp

 En las clases del paquete controller y service.imp aplique la inyección de dependencia utilizando la
anotación @Autowired.

documente el código que realice.

**Comment by JohnRM992** [comment]
Para la implementación de capa service se crean dos ramas nuevas:

tp6_issue4_capa_service_consejos
tp6_issue4_capa_service_servicios
