### ISSUE TITLE
Issue 8 tp 6 arreglar errores de sucursalcontroller

### ISSUE THREAD

**Issue by fedewf1** [fedewf1/repositorio-tp2#81]
Se detectaron multiples errores en el controller y servicios de sucursal. No puede agregar una nueva sucursal. La edicion y eliminacion la esta haciendo el controlador, deberia ser la capa servicio quien se encarge de eso.

Quitar tabla y usar cards, Agregar mas elementos/caracteristicas responsivas.

**Comment by JohnRM992** [comment]
Para la revisión de la sección Sucursales, se crea la rama:

 tp6_issue8_correciones_sucursales
