### ISSUE TITLE
Issue 3 TP7 Grupo45 En consejos, Servicios - mapear con anotaciones y relaciones. Indicar atributos con clave,

### ISSUE THREAD

**Issue by fedewf1** [fedewf1/repositorio-tp2#88]
Issue 3 Tp7 Grupo45************@~Jonathan R. M.***************
****Tal vez sea mejor dividir las issues donde se trabajen mas de un archivo.*****

Sobre
Consejos y
Servicios

1.-  Realizar el mapeo utilizando anotaciones pertenecientes
al paquete jakarta.persistence (@Entity, @Table, @Id, @Column, @OneToMany, @OneToOne etc.)

2.- En cada clase se debe indicar que atributo será la clave primaria (@Id), agregar un atributo de tipo Long
con nombre id.

3.- Por cada atributo indicar el nombre de la columna (@Column).

4.- Realice el mapeo de las relaciones:
***ver si hay mas relaciones, no estoy seguro de eso, pero el tp solo dice esto.**

Servicio – Empleado (el servicio solo tiene un único encargado (empleado)).
Empleado es una clase que representa a un empleado encargado de un servicio.

En cada clase agregue un atributo de tipo boolean denominado estado, este atributo indica si el objeto está
activo o no. Si se quiere eliminar un objeto se utilizará el estado = false, cuando se crea un nuevo objeto el
estado siempre tiene valor true.

5.- En el paquete reposotory cree las interfaces necesarias. Identifique los métodos para realizar las
consultas de los datos.

Mostrar los servicios según el día seleccionado.

6.- En el menú de navegación agregue una opción denominada “Gestión de datos”, donde se muestren las
opciones para dar de alta las diferentes entidades (redirige al respectivo formulario abm de cada entidad).
****hablar con los demas de como crear este archivo para evitar trabajar varios sobre el mismo. Es el nav.html
7.- Continúe con la documentación del código.

**Comment by JohnRM992** [comment]
Para la implementación de estos puntos, creo las ramas:

tp7_issue3_repository_servicios
tp7_issue3_repository_consejos
